### ISSUE TITLE
Big chunks of CGAL seem to be under the GPL

### ISSUE THREAD

**Issue by andybak** [Scrawk/CGALDotNet#2]
Core is LGPL: https://www.cgal.org/license.html

But lots of modules are GPL: https://doc.cgal.org/latest/Manual/packages.html

I'm wondering if you've got any insight into this that I've missed. I was hoping to use CGALDotNet in an Apache and MIT licenced project. I might have managed that by sticking to the LGPL parts (although I understand that makes Android builds problemmatic due to packaging).

However - GPL surely rules out any usage in non-GPL open source. And doesn't that mean CGALDotNet itself needs to be GPL as you're wrapping some of the GPL CGAL modules?

I'm not expecting but holding out a small hope you know a workaround for this as I'd love to use CGALDotNet.

**Comment by Scrawk** [comment]
I’m not very knowledgeable with licensing so really have no idea.

I’m happy to make CGALDotNet under what ever licence it should be. Guess I should change it GPL then? Or maybe LGPL?

**Comment by Scrawk** [comment]
CGALDotNet does not actually modify CGAL in anyway so might be able to be under a different licence.

**Comment by andybak** [comment]
> CGALDotNet does not actually modify CGAL in anyway so might be able to be under a different licence.

To the best of my understanding that's not true. The GPL doesn't require modification - only distribution.

**Comment by Scrawk** [comment]
Yeah, that was wishful thinking.

Looking into this and I need to change the license to GPL. 

Could in theory split it into GPL and LGPL parts but looks like the vast majority of CGAL is GPL.
